### DISCUSSION TITLE
rgd.yml

### DISCUSSION THREAD

**Discussion by eryajf** [eryajf/talk-opsre#1] [General]
```yml
owner: eryajf
repo: talk-opsre
type: issues
issues-owner: eryajf
issues-repo: talk-opsre

website:
  logo: https://avatars.githubusercontent.com/u/188568020?s=200&v=4
  title: TALK-OPSRE
  description: 认清不足，认识优秀，认知提升，共同成长。
  home: issues-labels
  home-layout: [label]
  label-category: [CMDB,CICD,K8S-Cluster-Manage,Docker-Tools,运维管理平台,更多]
  label-level: [L1, L2, L3, L4]
  built-date: 2025

manifest:
  name: TALK-OPSRE
  short_name: TALK-OPSRE
  start_url: /
  background_color: "#654FF0"
  theme_color: "#FFFFFF"
  display: standalone
  icon: https://avatars.githubusercontent.com/u/188568020?s=200&v=4
```
